name: CI - Build, Push images to Docker Hub and Deploy to Kubernetes

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    name: Build and Push Images to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      version: ${{ github.run_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Backend image
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/job-tracker-backend
          tags: |
            type=raw,value=${{ github.run_number }}
            type=raw,value=latest

      - name: Extract metadata for Frontend image
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/job-tracker-frontend
          tags: |
            type=raw,value=${{ github.run_number }}
            type=raw,value=latest

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./jobApplicationTrackerBackend
          file: ./jobApplicationTrackerBackend/DockerfileBackend
          push: true
          # backend-specific tags
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./jobApplicationTrackerFrontend
          file: ./jobApplicationTrackerFrontend/DockerfileFrontend
          push: true
          # frontend-specific tags
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

  deploy:
    name: Update Kubernetes Manifests
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Manifests Repository
        uses: actions/checkout@v4
        with:
          repository: milakirovski/job-application-tracker-kubernetes-manifests
          token: ${{ secrets.GH_PAT }}

      - name: Update Backend Image Tag
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/job-tracker-backend:${{ needs.build-and-push.outputs.version }}|g' backend-deployment.yaml

      - name: Update Frontend Image Tag
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/job-tracker-frontend:${{ needs.build-and-push.outputs.version }}|g' frontend-deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit. Working tree is clean."
            exit 0
          fi
          
          git commit -m "Update image tags to version ${{ needs.build-and-push.outputs.version }}"
          git push